### ISSUE TITLE
cBioPortal charts and graphs not rendering for v5.1

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/ARMORsmith#38]
The landing page of cBioPortal for the latest version does not have all of the default graphs and charts that previous versions (pre v5) have and custom charts and selections cannot be created. 

Cancer Type is also missing from the default boxes on the summary tab, which is essential for subsetting the dataset.

**Comment by artnasamran** [comment]
https://groups.google.com/g/cbioportal/c/hbMmRhkIvaY
